language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - pip install poetry
install:
  - poetry install

script:
  - flake8 .
  - mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers .
  - coverage run --source poche -m pytest -v
  - coverage report
  - codecov

before_deploy:
  - poetry build
deploy:
  - provider: releases
    token: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
      python: 3.6
  - provider: pypi
    username: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    skip_cleanup: true
    on:
      tags: true
      python: 3.6
